Resources:    
  DBCluster:
    Type: "AWS::RDS::DBCluster"
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBClusterIdentifier: "${self:service}-${self:provider.stage}-db-cluster"
      EnableHttpEndpoint: true
      Engine: aurora-postgresql
      EngineMode: serverless
      EngineVersion: "11"
      DatabaseName: test
      MasterUsername: possu
      MasterUserPassword: test
      StorageEncrypted: true
      UseLatestRestorableTime: true
