Resources:
  DBMasterSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: "${self:service}-${self:provider.stage}-DB-master-secret"
      Description: "RDS Master credentials for ${self:service}-${self:provider.stage}"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "possu", "host": "localhost.localstack.cloud", "port": "4510", "dbname": "test"}'
        # SecretStringTemplate: '{"username": "possu"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  DBAppSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: ${self:service}-${self:provider.stage}-DB-app-secret
      Description: 'RDS app credentials for ${self:service}-${self:provider.stage}'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "app", "host": "localhost.localstack.cloud", "port": "4510", "dbname": "exampledb"}'
        # SecretStringTemplate: '{"username": "app"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  APIKeySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: ${self:service}-${self:provider.stage}-API-key-secret
      Description: 'AppSync API KEY for ${self:service}-${self:provider.stage}'
      SecretString: ${appsync:apiKey.test}
